### PR TITLE
feat: add docker-compose.yaml for databases

### PR DESCRIPTION
**Pull request by kenjis**
- PostgreSQL 13
- SQL Server 2019
- MySQL 5.7

### CODE REVIEW

**Comment by kenjis** [comment]
Moved to `src/docker/`.

**Comment by lonnieezell** [comment]
Should we include MySQL or MariaDB also?

**Comment by kenjis** [comment]
Added MySQL.

**Review by lonnieezell — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Very nice, happy to have an official version of this available. Might even be worth mentioning in the framework User Guide?

**Pull request merged**
