### PR TITLE
feat: add MailHog to docker-compose.yaml

### PR DESCRIPTION
**Pull request by kenjis**
See https://github.com/mailhog/MailHog

### CODE REVIEW

**Comment by MGatner** [comment]
MailHog looks cool but hasn't had a release in 2 years. Is this what we want to endorse? Have you used it recently and verified it still works well?

**Comment by kenjis** [comment]
I checked it worked today.

Are there any other mail servers that are easy to build?

**Comment by MGatner** [comment]
I've never used such a service! I always mock the email class and capture output instead (see `Tatter\Outbox` for example). 

I'm interested in trying this though. Let's go with this one since you have experience with it.

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
Yes, this is just some lines in docker-compose.yaml.
If we find something better, it is very easy to change.

MailHog is also very easy. set `.env` and run docker-compose.
That's it. You can see sent mails in http://localhost:8025/

**Pull request merged**
