### PR TITLE
Update rector.php

### PR DESCRIPTION
**Pull request by kenjis**
Update from https://github.com/codeigniter4/shield/pull/811

### CODE REVIEW

**Comment by MGatner** [comment]
Consider moving Rector from `require-dev` to `require` based on our other thread.

**Comment by kenjis** [comment]
@MGatner What is it? Can you give me a reference?

Ah, this repo is devkit, and if you install this as dev dependency, it should also install rector?

**Comment by MGatner** [comment]
Correct! So our other libraries that depend on DevKit won't need to add Rector to their dev requirements. I think we want Rector everywhere so this would be a safe, central place to control the version.

**Comment by kenjis** [comment]
That makes sense! 
I sent PR #114

**Review by MGatner — APPROVED** [review]

**Pull request merged**
