### PR TITLE
chore: move rector from `require-dev` to `require`

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See https://github.com/codeigniter4/devkit/pull/111#issuecomment-1712987977

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
A consideration: since DevKit is available for anyone to use, do we want to be locking the Rector version? If we do, we end up managing this repo and could bottleneck other people's upgrades. If we don't, we would need to lock it in our own repos to whatever config we are using.

**Comment by MGatner** [comment]
@samsonasik opinion as well

**Review by samsonasik — APPROVED** [review]
Looks good

**Comment by kenjis** [comment]
@MGatner @samsonasik Ah, we cannot lock the version in this repo?
If we do,  other people who use this cannot upgrade their rector version.

> If we don't, we would need to lock it in our own repos to whatever config we are using.

Yes.

**Comment by kenjis** [comment]
After all, since rector is not yet stable, the best practice is for each project to lock in a version. Otherwise, `rector.php` may stop working.

If we lock the version in this repository, and even if we constantly update to the latest version, `rector.php` in the user's repository will not be automatically updated, which could cause rector to stop working.

I'm starting to feel like we should leave `require-dev` as it is.

**Comment by samsonasik** [comment]
pin rector to specific version is fine, on laminas, we are doing that, see

https://github.com/laminas/laminas-servicemanager-migration/blob/cdedb23f9df8480daead4dbef79b35f26fedcc86/composer.json#L19

**Comment by datamweb** [comment]
> If pin updated, then create new release of dev kit

last release of dev **Dec 22, 2022** but rector new version every week:smiley:. **dev** cannot act like a reactor.

**Comment by kenjis** [comment]
@MGatner I changed to `^0.18.3`.

**Comment by kenjis** [comment]
I think we can release a new devkit after merging this PR.

**Pull request merged**
