### PR TITLE
fix: skip AnnotationWithValueToAttributeRector

### PR DESCRIPTION
**Pull request by kenjis**
It requires PHP 8.0.

### CODE REVIEW

**Review by MGatner — APPROVED** [review]

**Comment by samsonasik** [comment]
The patch actually need to be in rector-phpunit to implements `MinPhpVersionInterface`

**Comment by samsonasik** [comment]
see https://github.com/rectorphp/rector-phpunit/pull/138

**Comment by MGatner** [comment]
That would make more sense!

**Comment by MGatner** [comment]
Thought actually: it doesn't look like we set a target PHP version, so won't the workflow version determine the target? This could cause problems if the workflow runs on 8.x for a project that supports 7.4

**Comment by samsonasik** [comment]
Rector will read composer.json minimal value:

```
"php": "^7.4",
```

 when not defined via:

```php
$rectorConfig->phpVersion(PhpVersion::PHP_74);
```

**Comment by samsonasik** [comment]
Rector 0.15.2 released with include the Min php version check for it https://github.com/rectorphp/rector/releases/tag/0.15.2

**Pull request closed without merging**
